[project]
name = "llm2024-competition-runner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ollama>=0.4.4",
    "polars>=1.16.0",
]
